### ISSUE TITLE
How to page items using getItemsByCAMLQuery

### ISSUE THREAD

**Issue by mauricionr** [OfficeDev/PnP-JS-Core#182]
#### Category
[ ] Enhancement

[ ] Bug

[X ] Question

#### Expected / Desired Behavior / Question
Page items using getItemsByCAMLQuery, maybe using getPaged

#### Observed Behavior
getItemsByCAMLQuery return a promise, how to get the next and prev items?

#### Steps to Reproduce

Thanks!

**Comment by patrick-rodgers** [comment]
Would encourage you to use the REST options whenever possible. The CAML was added to support legacy needs. You can see an example of paging in the samples add-in. [Example file](https://github.com/OfficeDev/PnP/blob/master/Samples/SharePoint.pnp-js-core/SharePoint.pnp-js-core/Samples/ReadListItemsPaged.html)

**Comment by mauricionr** [comment]
@patrick-rodgers this example don't use getItemsByCamlQuery,  i have some project that i use a lot of caml like, DateRageOverLap, Membership, and since this method return a promise i don't see how to paged the items...

I think that this method could be placed in Items class, i'm studing the code to make this feature.

got it?

**Comment by koltyakov** [comment]
Hi Mauricio,

Raw CAML and SharePoint itself have never been friendly to lists paging.
Sometimes you need to use RowLimit in a query and some additional condition which let you receive the next or previous chunk of data.

In something like that logic:

$pnp.sp.web.lists.getByTitle('Custom02').getItemsByCAMLQuery({ ViewXml: "<View><RowLimit>10</RowLimit><Query><Where><Gt><FieldRef Name='ID' /><Value Type='Number'>60</Value></Gt></Where></Query></View>" }).then(function(d) {
   console.log(d.map(function(d) {
      return d.Id;
   }));
});

Without getItemsByCAMLQuery, with top and skip, otherwise the logic have to be identical:

$pnp.sp.web.lists.getByTitle('Custom02').items.skip(61).top(10).get().then(function(d) {
   console.log(d.map(function(d) {
      return d.Id;
   }));
});

Where .top(N) will be transformed to $top=N,
and .skip(M) is just a helper to $skiptoken=Paged=TRUE&p_ID=M,
where M is an ID

**Comment by koltyakov** [comment]
Hi Mauricio,

Raw CAML and SharePoint itself have never been friendly to lists paging.
Sometimes you need to use RowLimit in a query and some additional condition which let you receive the next or previous chunk of data.

In something like that logic:

`$pnp.sp.web.lists.getByTitle('Custom02').getItemsByCAMLQuery({ ViewXml: "<View><RowLimit>10</RowLimit><Query><Where><Gt><FieldRef Name='ID' /><Value Type='Number'>60</Value></Gt></Where></Query></View>" }).then(function(d) {
   console.log(d.map(function(d) {
      return d.Id;
   }));
});`

Without getItemsByCAMLQuery, with top and skip, otherwise the logic have to be identical:

`$pnp.sp.web.lists.getByTitle('Custom02').items.skip(61).top(10).get().then(function(d) {
   console.log(d.map(function(d) {
      return d.Id;
   }));
});`

Where .top(N) will be transformed to $top=N,
and .skip(M) is just a helper to $skiptoken=Paged=TRUE&p_ID=M,
where M is an ID

**Comment by koltyakov** [comment]
Hi Mauricio,

Raw CAML and SharePoint itself have never been friendly to lists paging.
Sometimes you need to use RowLimit in a query and some additional condition which let you receive the next or previous chunk of data.

In something like that logic:

```javascript
$pnp.sp.web.lists.getByTitle('Custom02').getItemsByCAMLQuery({ ViewXml: "<View><RowLimit>10</RowLimit><Query><Where><Gt><FieldRef Name='ID' /><Value Type='Number'>60</Value></Gt></Where></Query></View>" }).then(function(d) {
   console.log(d.map(function(d) {
      return d.Id;
   }));
});
```

Without getItemsByCAMLQuery, with top and skip, otherwise the logic have to be identical:

```javascript
$pnp.sp.web.lists.getByTitle('Custom02').items.skip(61).top(10).get().then(function(d) {
   console.log(d.map(function(d) {
      return d.Id;
   }));
});
```

Where .top(N) will be transformed to $top=N,
and .skip(M) is just a helper to $skiptoken=Paged=TRUE&p_ID=M,
where M is an ID

**Comment by patrick-rodgers** [comment]
Going to close this as it appears answered with a solid code example. Please re-open if things are still not working or unclear. Thanks!
