### ISSUE TITLE
Samples/Documentation to be created?

### ISSUE THREAD

**Issue by alex-randall** [OfficeDev/PnP-JS-Core#71]
Here is a list of documentation/sample topics that I feel would help if people visit our site they can use our library immediately (along with API documentation of course, which is being worked on here: https://github.com/OfficeDev/PnP-JS-Core/issues/6).

Some or all of these maybe put in the wiki? Some may be in the sample project @patrick-rodgers demoed and/or both?  A lot of these I envision screenshots as well as actual code.

- How to use in Visual Studio Code
- How to use in Visual Studio 2015
- How to use in other tools (with NPM)
- How to use in Content Editor Web Part (see note)
- How to use in Script Editor Web Part  (see note)
- How to use in Provider Hosted SharePoint Add-In
- How to use in SharePoint Hosted SharePoint Add-In
- How to use in angularjs
- How to use in React
- Samples: how to get list items via REST (in TypeScript and JavaScript)
- many many more...

note: need to figure out where site owners, who don't use editors like Visual Studio Code (because of company policies of installing software on the desktop), etc, can instead reference/download pnp.min.js from:  a known CDN somewhere or somewhere in this repository (not link directly in that case, download first, then upload to a location of their choosing)?

Possible Tweaks to root readme.md

- Make focus on end user coming to this site for first time and using it immediately all near the top of the readme
- Add mission statement/make purpose of library clear
- Add Links to new "How to use" and sample pages above as well as forthcoming generated api documentation
 
Appreciate more discussion/comments about what should be here...
As well as people taking these on asap as this library may start getting a lot of hits on 5/4/2016.

**Comment by patrick-rodgers** [comment]
Hi Alex, this is a great list and we absolutely want to keep these points in mind - so I have moved the content to a [Yammer thread](https://www.yammer.com/itpronetwork/#/Threads/show?threadId=700777152) and will be closing this issue.

The reason is this doesn't represent a thing we can close/resolve atomically. Absolutely agree we need to grow on all these fronts - guidance, documentation, and samples. Did get a [samples project](https://github.com/OfficeDev/PnP/tree/dev/Samples/SharePoint.pnp-js-core) started as well to begin down that road.

**Comment by seaSide974** [comment]
hi, that would be great to have a sample for on premise 2013 too, without spfx :) thx
