### ISSUE TITLE
Remove remaining jQuery refs in src

### ISSUE THREAD

**Issue by patrick-rodgers** [OfficeDev/PnP-JS-Core#74]
Would like to see us get the remaining jQuery refs out of ./src There aren't many and would remove a dependency for users.

**Comment by alex-randall** [comment]
Agreed!  We need to have as few dependencies as possible so the widest array of people can use it.  Some companies have very specific restrictions on using "library x" or not.

**Comment by biste5** [comment]
I am looking into this, and seems the strongest dependencies on jQuery are on the _provisioning_ part.

Unfortunately, this isn't covered by tests, and I don't know how to test it at the moment.

Fix to change after a quick look:

- remove _jQuery.ajax_ calls: just one, it's basically done reusing _HttpClient_

- replace _jQuery.grep_ with a custom utility function, which should be called _grep_ or _fiter_ (any preference?). Does it have to be IE8 compatible?

- remove remaining references of _jQuery.Deferred_

I have started, but not sure how far I can go in the next few days; also because first of all I think I'll try to write few tests to cover existing lacks in methods to adjust.

Let me know if I should issue a WIP or how to best handle this

**Comment by patrick-rodgers** [comment]
Thanks for taking a look, that seems like a good list, I didn't think there was too much left. As for IE8 - no, don't worry about it. If someone needs IE8 support they can log a bug and we can revisit.

**Comment by mike-morrison** [comment]
@biste5 @patrick-rodgers I don't think we need a custom function.  [We can just use the built-in array.filter](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/filter#Browser_compatibility).

**Comment by biste5** [comment]
Thanks @mike-morrison and @patrick-rodgers !

**Comment by biste5** [comment]
I've covered I think 80% of the stuff, it's pushed atm to 
https://github.com/biste5/PnP-JS-Core/tree/dev_74

What remains it's all in [objectfiles.ts](https://github.com/OfficeDev/PnP-JS-Core/blob/dev/src/sharepoint/provisioning/objecthandlers/objectfiles/objectfiles.ts)

- jQuery.get to get raw content of a file ([line 25](https://github.com/OfficeDev/PnP-JS-Core/blob/dev/src/sharepoint/provisioning/objecthandlers/objectfiles/objectfiles.ts#L25)), and definition of a web part ([Line 100](https://github.com/OfficeDev/PnP-JS-Core/blob/dev/src/sharepoint/provisioning/objecthandlers/objectfiles/objectfiles.ts#L100)) (?)
- jQuery.when.apply at [Line 31](https://github.com/OfficeDev/PnP-JS-Core/blob/dev/src/sharepoint/provisioning/objecthandlers/objectfiles/objectfiles.ts#L31), looks a bit fragile to me, and I didn't know yet how to convert it to Promise safely
- jQuery.extend, mainly at [Line 179](https://github.com/OfficeDev/PnP-JS-Core/blob/dev/src/sharepoint/provisioning/objecthandlers/objectfiles/objectfiles.ts#L179). (That one at [line 27](https://github.com/OfficeDev/PnP-JS-Core/blob/dev/src/sharepoint/provisioning/objecthandlers/objectfiles/objectfiles.ts#L27) can be easily rewritten using vanilla JS)

**Comment by patrick-rodgers** [comment]
Closing this, nice work Massimo.
